name: Build UI executable

on:
  push:
    paths:
      - '.github/workflows/*'
      - 'src/**'
  pull_request:
    paths:
      - '.github/workflows/*'
      - 'src/**'
  workflow_dispatch:

jobs:
    build_executable:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ windows-latest ]

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v3
              with:
                python-version: '3.x'

            - name: Install dependencies
              run: |
                python -m pip install -r requirements.txt
                python -m pip install tinyaes git+https://github.com/pyinstaller/pyinstaller.git

            - name: Get short SHA (win32)
              if: matrix.os == 'windows-latest'
              run: echo "SHORT_SHA=$($env:GITHUB_SHA.SubString(0,7))" >> $env:GITHUB_ENV
            - name: Get short SHA (linux)
              if: matrix.os == 'ubuntu-latest'
              run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

            - name: Build application
              env:
                my_key: ${{ secrets.pyinstaller_pass }}
              run: pyinstaller --onefile --key "$env:my_key" -n py-patcher-ui --distpath . launcher.py -w --splash splash.png

            - name: Push app artifact
              uses: actions/upload-artifact@v3
              with:
                name: py-patch-${{ matrix.os }}
                path: |
                  README.md
                  LICENSE
                  py-patcher-ui
                  py-patcher-ui.exe
                retention-days: 7

            - name: Upload win32 binaries for release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              if: |
                github.event_name == 'workflow_dispatch' &&
                matrix.os == 'windows-latest'
              run: |
                compress-archive py-patcher-ui.exe, LICENSE, README.md py-patcher-ui-windows.zip
                gh release upload $env:SHORT_SHA py-patcher-ui-windows.zip.zip
